
baseURL = "https://akitect.io"
defaultContentLanguage = "vi"
title = "Akitect"
# Enable syntax highlighting
pygmentsStyle = "monokai"
pygmentsCodeFences = true
pygmentsUseClasses = true
# Enable robots.txt
enableRobotsTXT = true

# theme
theme = "gohugo-courses"
