[[main]]
name = "Trang chủ"
pageRef = "/"
weight = 1


[[main]]
name = "Nghiên cứu"
pageRef = "/labs"
weight = 2

[[main]]
name = "Thực chiến"
pageRef = "/courses"
weight = 3

# [[main]]
# name = "AI"
# pageRef = "/ai"
# weight = 4