[[main]]
name = "Home"
pageRef = "/"
weight = 1


[[main]]
name = "Labs"
pageRef = "/labs"
weight = 2

[[main]]
name = "AI"
pageRef = "/ai"
weight = 3

[[main]]
name = "Courses"
pageRef = "/courses"
weight = 4

