[google_adsense]
url = "https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6342139522924885"

[google_new]
hide = false
url = "https://news.google.com/publications/CAAqBwgKMKrRpwwwvNm1BA?hl=vi&gl=VN&ceid=VN%3Avi"

[google_site_verification]
key = "kOA7UqBkoO-Trr2fcevW1nee1flUJdFq8HCbGtzdyXA"

[analytics]
enable = true

[analytics.google]
id = "G-HK7K88DBRS"
anonymizeIP = true


[[social]]
href = "https://www.facebook.com/akitect.io"
icon = "fa fa-facebook"

[[social]]
href = "https://www.instagram.com/akitectio"
icon = "fa fa-instagram"

[[social]]
href = "https://www.linkedin.com/in/akitect-io"
icon = "fa fa-linkedin"

[[social]]
href = "https://youtube.com/akitect"
icon = "fa fa-youtube"

[[social]]
href = "https://github.com/akitectio"
icon = "fa fa-github"

[[social]]
href = "https://t.me/+i45gRt8FGyRkOGY1"
icon = "fa fa-telegram"

[home]
avatar = "/avatar.png"
title = "Hello Everyone!"
description = " I'm Duy, a lover of technology, programming,solution architect and everything related to IT."

[courses]
seo_image = "/courses.webp"

[labs]
seo_image = "/labs.webp"

[seo]
default_author = "DUY TRAN, akitect.io@gmail.com"
default_keywords = "akitect, akitect.io, kubernetes, docker, devops, cloud, cloud-native, microservices, architecture, design, software, development, programming, coding"
default_description = "Akitect is a blog about software development, programming, coding, software architecture, software design, cloud-native, microservices, devops, kubernetes, docker, cloud, and more."
default_image = "/images/akitect.png"
fb_app_id = "1234567890"
