[google_new]
hide = false
url = "https://news.google.com/publications/CAAqBwgKMKrRpwwwvNm1BA?hl=vi&gl=VN&ceid=VN%3Avi"

[google_site_verification]
key = "kOA7UqBkoO-Trr2fcevW1nee1flUJdFq8HCbGtzdyXA"

[analytics]
enable = true

[analytics.google]
id = "G-HK7K88DBRS"
anonymizeIP = true


[[social]]
href = "https://www.facebook.com"
icon = "fa fa-facebook"

[[social]]
href = "https://www.instagram.com"
icon = "fa fa-instagram"

[[social]]
href = "https://www.snapchat.com"
icon = "fa fa-snapchat"

[[social]]
href = "https://www.twitter.com"
icon = "fa fa-twitter"

[home]
avatar = "/avatar.png"
title = "Hello Everyone!"
description = " I'm Duy, a lover of technology, programming,solution architect and everything related to IT."

[courses]
seo_image = "/courses.webp"

[labs]
seo_image = "/labs.webp"

[seo]
default_author = "DUY TRAN, akitect.io@gmail.com"
default_keywords = "akitect, akitect.io, kubernetes, docker, devops, cloud, cloud-native, microservices, architecture, design, software, development, programming, coding, programming languages, golang, python, javascript, typescript, react, vue, angular, nodejs, express, nestjs, spring, springboot, java, kotlin, rust, c, c++, c#, dotnet, dotnetcore, dotnet5, dotnet6, aspnet, aspnetcore, aspnet5, aspnet6, web, webdev, webdevelopment, webdesign, webdesigner, webdeveloper, frontend, backend, fullstack, fullstackdeveloper, fullstackdevelopment, fullstackdesign, fullstackdesigner, fullstackdev, fullstackdevs"
default_description = "Akitect is a blog about software development, programming, coding, software architecture, software design, cloud-native, microservices, devops, kubernetes, docker, cloud, and more."
default_image = "/images/akitect.png"
