[labs]
title = "Nghiên Cứu"
description = "Nơi chia sẻ những kiến thức nghiên cứu"

[courses]
title = "Thực Chiến"
description = "Nơi chia sẻ những kiến thức thực chiến, kinh nghiệm làm việc thực tế"

[ai]
title = "AI - Trí Tuệ Nhân Tạo"
description = "Chuyên mục blog cung cấp thông tin cập nhật và ứng dụng thực tiễn về AI"

